repos:
  - repo: https://github.com/pre-commit/mirrors-black
    rev: v23.3.0  # Use the latest version
    hooks:
      - id: black
        language_version: python3  # Specify the Python version

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4  # Use the latest version
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/pylint
    rev: v2.17.5  # Use the latest version
    hooks:
      - id: pylint
